#+title: The Blank Page and Me
#+date: 2026-03-30
#+tags[]: writing
#+tags[]: essays

I love reading interesting people and their work — especially essays from [[https://www.paulgraham.com/][Paul Graham]], [[https://patrickcollison.com/][Patrick Collison]], [[https://guzey.com][Alexey Guzey]], [[https://gwern.net][Gwern]], [[https://sive.rs/][Derek Sivers]] and many other cool people. So I decided to start my own journey as a writer to improve my skills and create more!

I was putting off writing because of "absence of ideas" and "awkwardness" of publishing rough posts, especially as a perfectionist. Obviously, these reasons are more of an excuse rather than being rational.

The problem of having "nothing" to write about is mostly illusory. I think every living human being has things that they consider interesting. Just going outside and letting your mind wander can bring up many such ideas. You start with one simple thing and often end up elaborating and connecting it to other thoughts.

The mentality of a perfectionist mind is the enemy of doing. You'll not develop writing skills if there won't be /any/ writing. I think it's okay if it feels weird or you are not satisfied with it since you are comparing yourself with writers with greater experience. But the truth is that they also started from zero. I assume this principle of just starting doing things applies to many things in the world. Yet I believe it's especially true for writing since it's a process where you progress by /doing/ it a lot.

Why should I even consider writing? I think writing has many benefits. The one that I value the most is the way it makes you /think/. It's not only about representing your ideas as a text — when you write about something, you'll think through this idea from many angles. It makes your thought process clear and distinct.

I think there's be a lot of joy writing about things that interest me. I hope for many more moments with The Blank Page and Me!
